name: Automatic Release

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger release for tags like v1.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Zip Archive
        run: |
          zip -r release-${{ github.ref_name }}.zip . -x "*.git*" ".github/*"
      
      - name: Create GitHub Release & Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: release-${{ github.ref_name }}.zip